import { AtmOutlined } from "@mui/icons-material";
import { image } from "framer-motion/client";

const chartData = [
  { name: "Jan", sale: 90_000 },
  { name: "Feb", sale: 100_000 },
  { name: "Mar", sale: 160_000 },
  { name: "Apr", sale: 135_000 },
  { name: "May", sale: 2_000 },
  { name: "Jun", sale: 50_000 },
  { name: "Jul", sale: 90_000 },
  { name: "Aug", sale: 100_000 },
  { name: "Sep", sale: 160_000 },
  { name: "Oct", sale: 200_000 },
  { name: "Nov", sale: 2_000 },
  { name: "Dec", sale: 50_000 },
];
const featureData = [
  {
    id: 1,
    title: "Revanue",
    mony: "$2,415",
    monyStatus: "-11.4",
    status: "down",
    desc: "Compared to last month",
  },
  {
    id: 2,
    title: "Revanue",
    mony: "$2,415",
    monyStatus: "-11.4",
    status: "down",
    desc: "Compared to last month",
  },
  {
    id: 3,
    title: "Cost",
    mony: "$2,415",
    monyStatus: "+2.4",
    status: "down",
    desc: "Compared to last month",
  },
];
const newUsersRecently = [
  {
    id: 1,
    username: "Mohammad",
    skills: "Web Developer",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 2,
    username: "Ali",
    skills: "Mobile Developer",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 3,
    username: "Sara",
    skills: "UI/UX Designer",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 4,
    username: "Hossein",
    skills: "Data Analyst",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 5,
    username: "Zahra",
    skills: "Backend Developer",
    profile: "images/profile/Admin-Profile.png",
  },
];
const latestTransActionData = [
  {
    id: 1,
    username: "Mohammad",
    date: "2023-01-15",
    amount: 245,
    status: "Approved",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 2,
    username: "Ali",
    date: "2023-06-22",
    amount: 378,
    status: "Pending",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 3,
    username: "Sara",
    date: "2024-03-10",
    amount: 150,
    status: "Declined",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 4,
    username: "Hossein",
    date: "2024-09-05",
    amount: 890,
    status: "Approved",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 5,
    username: "Zahra",
    date: "2025-02-18",
    amount: 320,
    status: "Pending",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 6,
    username: "Reza",
    date: "2025-07-01",
    amount: 500,
    status: "Approved",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 7,
    username: "Fatima",
    date: "2025-07-10",
    amount: 675,
    status: "Declined",
    profile: "images/profile/Admin-Profile.png",
  },
  {
    id: 8,
    username: "Ehsan",
    date: "2025-07-16", // امروز
    amount: 200,
    status: "Pending",
    profile: "images/profile/Admin-Profile.png",
  },
];
const userRows = [
  {
    id: 1,
    username: "Mohammad",
    avatar: "images/profile/Admin-Profile.png",
    status: "active",
    transaction: "$110",
    lastLogin: "2025-07-15",
  },
  {
    id: 2,
    username: "Ali",
    avatar: "images/profile/Admin-Profile.png",
    status: "non-action",
    transaction: "$85",
    lastLogin: "2025-07-14",
  },
  {
    id: 3,
    username: "Sara",
    avatar: "images/profile/Admin-Profile.png",
    status: "active",
    transaction: "$230",
    lastLogin: "2025-07-13",
  },
  {
    id: 4,
    username: "Hossein",
    avatar: "images/profile/Admin-Profile.png",
    status: "suspended",
    transaction: "$150",
    lastLogin: "2025-07-12",
  },
  {
    id: 5,
    username: "Zahra",
    avatar: "images/profile/Admin-Profile.png",
    status: "non-action",
    transaction: "$320",
    lastLogin: "2025-07-11",
  },
  {
    id: 6,
    username: "Reza",
    avatar: "images/profile/Admin-Profile.png",
    status: "active",
    transaction: "$45",
    lastLogin: "2025-07-10",
  },
  {
    id: 7,
    username: "Fatima",
    avatar: "images/profile/Admin-Profile.png",
    status: "suspended",
    transaction: "$190",
    lastLogin: "2025-07-09",
  },
  {
    id: 8,
    username: "Ehsan",
    avatar: "images/profile/Admin-Profile.png",
    status: "non-action",
    transaction: "$275",
    lastLogin: "2025-07-16",
  },
  {
    id: 9,
    username: "Leila",
    avatar: "images/profile/Admin-Profile.png",
    status: "active",
    transaction: "$90",
    lastLogin: "2025-07-08",
  },
  {
    id: 10,
    username: "Amir",
    avatar: "images/profile/Admin-Profile.png",
    status: "suspended",
    transaction: "$400",
    lastLogin: "2025-07-07",
  },
  {
    id: 11,
    username: "Neda",
    avatar: "images/profile/Admin-Profile.png",
    status: "non-action",
    transaction: "$135",
    lastLogin: "2025-07-06",
  },
];
const productRows = [
  {
    id: 1,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Laptop",
    price: "$120",
  },
  {
    id: 2,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Smartphone",
    price: "$80",
  },
  {
    id: 3,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Tablet",
    price: "$95",
  },
  {
    id: 4,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Headphones",
    price: "$30",
  },
  {
    id: 5,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Smartwatch",
    price: "$55",
  },
  {
    id: 6,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Camera",
    price: "$200",
  },
  {
    id: 7,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Printer",
    price: "$75",
  },
  {
    id: 8,
    avatar: "images/profile/Admin-Profile.png",
    productName: "Monitor",
    price: "$110",
  },
];

export {
  chartData,
  featureData,
  newUsersRecently,
  latestTransActionData,
  userRows,
  productRows,
};
